// generated by ChatGPT
// getCombinations(['a', 'b', 'c'], 2)
//   -> returns [[a, b], [a, c], [b, c]]

function getCombinations(items, size) {
  const result = [];

  function combine(start, current) {
      if (current.length === size) {
          result.push([...current]); // Add the combination to the results
          return;
      }

      for (let i = start; i < items.length; i++) {
          current.push(items[i]);    // Add the current item
          combine(i + 1, current);  // Recurse, incrementing the start index
          current.pop();            // Backtrack to try other combinations
      }
  }

  combine(0, []); // Start from index 0 with an empty combination
  return result;
}

module.exports = getCombinations;
