PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    on_warn: fail
    requires_files: true
    include:
      - '**/*.rb'
      - '**/Gemfile'
    problem_on_unmodified_line: ignore
