AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
