AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - Gemfile.lock
    - 2017/
    - 2018/

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
