AllCops:
  NewCops: enable

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
