// generated by ChatGPT
// getPermutations(['a', 'b'], 2)
//   -> returns [[a, b], [b, a], [a, a], [b, b]]

function getPermutations(chars, spots) {
  const result = [];

  function permute(current) {
      if (current.length === spots) {
          result.push([...current]); // Add a copy of the current permutation
          return;
      }

      for (let char of chars) {
          current.push(char);       // Add a character to the current permutation
          permute(current);         // Recurse to fill the next spot
          current.pop();            // Backtrack by removing the last added character
      }
  }

  permute([]); // Start with an empty array
  return result;
}

module.exports = getPermutations;
